Bar chart with click
tingxuanz/biojs-vis-pca pull request #5
Opened 2017-01-06 05:40 UTC by tingxuanz

Hi @rowlandm , I have opened a pull request. You can review the code now!

2017-01-06 06:36 UTC, rowlandm requested changes

2017-01-06 06:36 UTC, rowlandm commented on examples/simple.js
> +var colors = ["DarkOrchid", "Orange", "DodgerBlue", "Blue","BlueViolet","Brown", "Deeppink", "BurlyWood","CadetBlue",
What happens when we have more types than samples?

2017-01-06 06:36 UTC, rowlandm commented on examples/simple.js
> +var colorBy = {SampleType: ["0", "Day1", "Day2","Day3", "Day4", "Day5", "Day6", "Day7", "ESRP KD", "CTRL", "RBM47 KD"], ExperimentalSeries: ["PRJNA304414", "PRJNA304419", "PRJNA304418"]};
This should be programatically done.

2017-01-06 06:36 UTC, rowlandm commented on examples/simple.js
> +var colorOptions = ["SampleType", "ExperimentalSeries"];
This should be done programatically

2017-01-06 06:36 UTC, rowlandm commented on examples/simple.js
> +    if (chosenOption.id === "SampleType") {
Won't be able to hardcode this if we don't know what values we are getting. Will need to be done programatically.

2017-01-06 06:36 UTC, rowlandm commented on examples/simple.js
> +      var bars = d3.selectAll(".bar")
Why are there two of these? One is on line 243?

2017-01-06 06:36 UTC, rowlandm commented on lib/index.js
> +    var full_width = 1300;
Perhaps we should be passing these in via options....

2017-01-08 22:56 UTC, tingxuanz commented on examples/simple.js
> +var colors = ["DarkOrchid", "Orange", "DodgerBlue", "Blue","BlueViolet","Brown", "Deeppink", "BurlyWood","CadetBlue",
![fireshot capture 1 - - http___localhost_9090_examples_simple](https://cloud.githubusercontent.com/assets/17842286/21754295/79eacaa2-d651-11e6-86de-e5a8ef38173e.png)
You can check the screenshot to see what happens if we have more options than available colors.
The colors will be used repeatedly.

2017-01-08 22:57 UTC, tingxuanz commented on examples/simple.js
> +var colorBy = {SampleType: ["0", "Day1", "Day2","Day3", "Day4", "Day5", "Day6", "Day7", "ESRP KD", "CTRL", "RBM47 KD"], ExperimentalSeries: ["PRJNA304414", "PRJNA304419", "PRJNA304418"]};
got it, will start soon

2017-01-08 22:58 UTC, tingxuanz commented on examples/simple.js
> +    if (chosenOption.id === "SampleType") {
got it, will start soon

2017-01-08 22:58 UTC, tingxuanz commented on lib/index.js
> +    var full_width = 1300;
yes, I agree

2017-01-08 23:02 UTC, tingxuanz commented on examples/simple.js
> +      var bars = d3.selectAll(".bar")
This is because when we re-render a graph, it is actually a new one. We need to add the onclick event listener every time we draw a new graph.

2017-01-08 23:20 UTC, rowlandm commented on examples/simple.js
> +var colors = ["DarkOrchid", "Orange", "DodgerBlue", "Blue","BlueViolet","Brown", "Deeppink", "BurlyWood","CadetBlue",
OK. Thanks. How many colours should we default to?\

Can we also try doing that programmatically? ie. http://bl.ocks.org/aaizemberg/78bd3dade9593896a59d

2017-01-08 23:20 UTC, rowlandm commented on examples/simple.js
> +      var bars = d3.selectAll(".bar")
Can't we store that in a function then?

2017-01-08 23:26 UTC, tingxuanz commented on examples/simple.js
> +      var bars = d3.selectAll(".bar")
ok, I will try

2017-01-08 23:37 UTC, tingxuanz commented on examples/simple.js
> +var colors = ["DarkOrchid", "Orange", "DodgerBlue", "Blue","BlueViolet","Brown", "Deeppink", "BurlyWood","CadetBlue",
If we don't want to specify colors, we can just use d3.scale.category10() or d3.scale.category20()

2017-01-08 23:38 UTC, rowlandm commented on examples/simple.js
> +var colors = ["DarkOrchid", "Orange", "DodgerBlue", "Blue","BlueViolet","Brown", "Deeppink", "BurlyWood","CadetBlue",
Is there a category100()?

2017-01-08 23:42 UTC, tingxuanz commented on examples/simple.js
> +var colors = ["DarkOrchid", "Orange", "DodgerBlue", "Blue","BlueViolet","Brown", "Deeppink", "BurlyWood","CadetBlue",
just check the API, only category 10 and category 20 are available.

2017-01-08 23:43 UTC, rowlandm commented on examples/simple.js
> +var colors = ["DarkOrchid", "Orange", "DodgerBlue", "Blue","BlueViolet","Brown", "Deeppink", "BurlyWood","CadetBlue",
OK. Category 20 is fine.

2017-01-10 06:40 UTC, rowlandm approved these changes

2017-01-10 23:04 UTC, merged