modify the approach to changing color and showing different PCs
tingxuanz/biojs-vis-pca pull request #9
Opened 2017-01-24 03:37 UTC by tingxuanz

Hi @rowlandm , you can review how colors are changed and different principle components are showed in this pull request.

2017-01-24 05:51 UTC, rowlandm requested changes

2017-01-24 05:51 UTC, rowlandm commented on examples/simple.js
> +    we need to creaet radio button elements in the form for each groupByoption.
create instead of creaet

2017-01-24 05:51 UTC, rowlandm commented on examples/simple.js
> +        d.PC3 = +d.PC3;
I'm not sure why this is hardcoded? Could we calculate this based on the number of PCA components we are going to show?

2017-01-24 05:51 UTC, rowlandm commented on examples/simple.js
>          xDomain: "PC1",
Not sure why this is hardcoded?

2017-01-24 05:51 UTC, rowlandm commented on lib/index.js
> +    d3.select("#colorSelect")
We shouldn't have triggers inside the index.js. They should be outside to keep flexibility.

2017-01-24 05:51 UTC, rowlandm commented on lib/index.js
> +    d3.select(".brushButton")
We shouldn't have triggers inside the index.js. They should be outside to keep flexibility.

2017-01-24 05:57 UTC, tingxuanz commented on examples/simple.js
>          xDomain: "PC1",
I just try several values and choose the value that looks better.

2017-01-24 06:06 UTC, tingxuanz commented on examples/simple.js
> +        d.PC3 = +d.PC3;
Then I think I need to move this piece of code to index.js. Because in simple.js I only read tsv files once and draw the default graph.

2017-01-24 06:06 UTC, rowlandm commented on examples/simple.js
>          xDomain: "PC1",
Sorry - I meant the value xDomain:"PC1"

2017-01-24 06:10 UTC, tingxuanz commented on lib/index.js
> +    d3.select(".brushButton")
I will try moving these triggers to a separate .js file which is in the same directory as index.js.
Do you think that is a feasible approach?

2017-01-24 06:12 UTC, tingxuanz commented on examples/simple.js
>          xDomain: "PC1",
The default graph uses PC1 and PC2, so I just hardcode these values for convenience. I will modify it later to use variables.

2017-01-24 06:14 UTC, rowlandm commented on examples/simple.js
>          xDomain: "PC1",
sorry - these are defaults. I see. That's fine.

2017-01-24 06:15 UTC, rowlandm commented on lib/index.js
> +    d3.select(".brushButton")
I think that would be in the simple.js. But the call inside to the index.js would be a function that does this.

2017-01-24 06:15 UTC, rowlandm commented on examples/simple.js
> +        d.PC3 = +d.PC3;
I'm not sure you can.....

2017-01-25 01:56 UTC, rowlandm approved these changes
That looks OK to me.

2017-01-25 02:03 UTC, merged